### ISSUE TITLE
error with layout parsing when processing the large size pdf file

### ISSUE THREAD

**Issue by xeon-ye** [peakhell/OCRIntegrator#3]
2024-06-28 14:50:59 - INFO - /home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py - line 985 - OCR: page 19 cost time: 0.17715859413146973
[06/28/2024-14:50:59] [TRT] [E] 3: [executionContext.cpp::setInputShape::2068] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2068, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
INFO:     192.168.3.26:59210 - "POST /layout/file HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/routers/ocr.py", line 48, in detect_layout_by_file
    result = ocr_service.detect_layout(file_type, file_io)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/service/layer.py", line 16, in detect_layout
    return self.ocr_adapter.detect_layout(file_type, file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/adapter/deepdoc_adapter.py", line 24, in detect_layout
    return self.pdf_parser.__call__(file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 1001, in __call__
    self.__images__(fnm, zoomin)
  File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 984, in __images__
    self._ocr(i + 1, img, chars, zoomin)
  File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 244, in _ocr
    bxs = self.ocr.detect(np.array(img))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 545, in detect
    dt_boxes, elapse = self.text_detector(img)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 460, in __call__
    raise e
  File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 458, in __call__
    outputs = TextDetector._predictor.run(None, input_dict)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 165, in run
    trt_outputs = self.infer(inputs)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 158, in infer
    self.stream.synchronize()
pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: an illegal memory access was encountered
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFreeHost failed: an illegal memory access was encountered
[2024年1-5月合同上部分五金造转.pdf](https://github.com/user-attachments/files/16025499/2024.1-5.pdf)

**Comment by peakhell** [comment]
> 2024-06-28 14:50:59 - INFO - /home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py - line 985 - OCR: page 19 cost time: 0.17715859413146973 [06/28/2024-14:50:59] [TRT] [E] 3: [executionContext.cpp::setInputShape::2068] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2068, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.) INFO: 192.168.3.26:59210 - "POST /layout/file HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi result = await app( # type: ignore[func-returns-value] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in **call** return await self.app(scope, receive, send) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in **call** await self.middleware_stack(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in **call** raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in **call** await self.app(scope, receive, _send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in **call** await self.middleware_stack(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app await route.handle(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle await self.app(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app response = await func(request) ^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app raw_response = await run_endpoint_function( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function return await dependant.call(**values) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/routers/ocr.py", line 48, in detect_layout_by_file result = ocr_service.detect_layout(file_type, file_io) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/service/layer.py", line 16, in detect_layout return self.ocr_adapter.detect_layout(file_type, file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/adapter/deepdoc_adapter.py", line 24, in detect_layout return self.pdf_parser.**call**(file_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 1001, in **call** self.**images**(fnm, zoomin) File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 984, in **images** self._ocr(i + 1, img, chars, zoomin) File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 244, in _ocr bxs = self.ocr.detect(np.array(img)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 545, in detect dt_boxes, elapse = self.text_detector(img) ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 460, in **call** raise e File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 458, in **call** outputs = TextDetector._predictor.run(None, input_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 165, in run trt_outputs = self.infer(inputs) ^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 158, in infer self.stream.synchronize() pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFreeHost failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFree failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFreeHost failed: an illegal memory access was encountered [2024年1-5月合同上部分五金造转.pdf](https://github.com/user-attachments/files/16025499/2024.1-5.pdf)

I'm checking.

**Comment by peakhell** [comment]
> 2024-06-28 14:50:59 - INFO - /home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py - line 985 - OCR: page 19 cost time: 0.17715859413146973 [06/28/2024-14:50:59] [TRT] [E] 3: [executionContext.cpp::setInputShape::2068] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2068, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.) INFO: 192.168.3.26:59210 - "POST /layout/file HTTP/1.1" 500 Internal Server Error ERROR: Exception in ASGI application Traceback (most recent call last): File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi result = await app( # type: ignore[func-returns-value] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in **call** return await self.app(scope, receive, send) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in **call** await super().**call**(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in **call** await self.middleware_stack(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in **call** raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in **call** await self.app(scope, receive, _send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in **call** await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in **call** await self.middleware_stack(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app await route.handle(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle await self.app(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app await wrap_app_handling_exceptions(app, request)(scope, receive, send) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app raise exc File "/home/xeon/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app await app(scope, receive, sender) File "/home/xeon/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app response = await func(request) ^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app raw_response = await run_endpoint_function( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/.local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function return await dependant.call(**values) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/routers/ocr.py", line 48, in detect_layout_by_file result = ocr_service.detect_layout(file_type, file_io) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/service/layer.py", line 16, in detect_layout return self.ocr_adapter.detect_layout(file_type, file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/adapter/deepdoc_adapter.py", line 24, in detect_layout return self.pdf_parser.**call**(file_path) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 1001, in **call** self.**images**(fnm, zoomin) File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 984, in **images** self._ocr(i + 1, img, chars, zoomin) File "/home/xeon/OCRIntegrator/app/deepdoc/parser/pdf_parser.py", line 244, in _ocr bxs = self.ocr.detect(np.array(img)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 545, in detect dt_boxes, elapse = self.text_detector(img) ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 460, in **call** raise e File "/home/xeon/OCRIntegrator/app/deepdoc/vision/ocr.py", line 458, in **call** outputs = TextDetector._predictor.run(None, input_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 165, in run trt_outputs = self.infer(inputs) ^^^^^^^^^^^^^^^^^^ File "/home/xeon/OCRIntegrator/app/deepdoc/tensorrt_engine.py", line 158, in infer self.stream.synchronize() pycuda._driver.LogicError: cuStreamSynchronize failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFreeHost failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFree failed: an illegal memory access was encountered PyCUDA WARNING: a clean-up operation failed (dead context maybe?) cuMemFreeHost failed: an illegal memory access was encountered [2024年1-5月合同上部分五金造转.pdf](https://github.com/user-attachments/files/16025499/2024.1-5.pdf)

How much VRAM do you have? It could be caused by insufficient VRAM.

**Comment by xeon-ye** [comment]
Ubuntu 22 ,128g ram,4090
